### ISSUE TITLE
droneBuildFeed.refreshEntry not found

### ISSUE THREAD

**Issue by volker-raschek** [jigkoxsee/vscode-droneci#4]
When I click on the refresh button I receive the following error message:

```bash
command 'droneBuildFeed.refreshEntry' not found
```

The values `droneci.server` and `droneci.token` are defined in my vscode settings. The value `droneBuildFeed.refreshEntry` is not available.

**Comment by rockxsj** [comment]
+1

**Comment by ntimo** [comment]
I had the same issue, and after restarting VSCode it just worked :D
